version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: timex
    versions:
    - 3.6.3
    - 3.6.4
    - 3.7.1
    - 3.7.3
  - dependency-name: excoveralls
    versions:
    - 0.13.4
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
